name: note_app_ui
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # <-- This line should be here!

flutter_icons: # <-- Moved out of dev_dependencies
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
